### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by ethanaobrien** [nenge123/emulatorjs#1]
Just want to make sure you saw that [I added a licence here](https://github.com/ethanaobrien/emulatorjs/blob/main/LICENSE). 

Please make sure you state the changes from [the original emulatorjs repository](https://github.com/ethanaobrien/emulatorjs)

**Comment by nenge123** [comment]
what are you think?

	
nenge123
Feb 16, 2022, 10:48 PM UTC

Hi nenge123,

I'm contacting you on behalf of GitHub because we've received a DMCA takedown notice regarding the following content:

https://github.com/nenge123/emulatorjs/tree/master/cores
https://github.com/nenge123/emulatorjs/blob/master/emulator.js
https://github.com/nenge123/emulatorjs/blob/master/emulator.min.js
https://github.com/nenge123/emulatorjs/blob/master/extract7z.min.js
https://github.com/nenge123/emulatorjs/blob/master/extractzip.min.js
https://github.com/nenge123/emulatorjs/blob/master/libunrar.js.mem
https://github.com/nenge123/emulatorjs/blob/master/libunrar.min.js
https://github.com/nenge123/emulatorjs

We're giving you 1 business day to make the changes identified in the following notice:

https://github.zendesk.com/attachments/token/Lh1EiAPfyn0DujXRaKsolMTm3/?name=2022-02-16-emulatorjs.rtf

If you need to remove specific content from your repository, simply deleting it via a commit won't resolve the alleged infringement. Instead, you must follow these instructions to remove the content from your repository's history, even if you don't think it's sensitive:

https://docs.github.com/articles/remove-sensitive-data

Once you've made changes, please reply to this message and let us know. If you don't tell us that you've made changes within the next 1 business day, we'll need to disable the entire repository according to our GitHub DMCA Takedown Policy:

https://docs.github.com/articles/dmca-takedown-policy/

If you believe your content on GitHub was mistakenly disabled by a DMCA takedown request, you have the right to contest the takedown by submitting a counter notice, as described in our DMCA Takedown Policy.

PLEASE NOTE: It is important that you reply to this message within 1 business day to tell us whether you've made changes. If you do not, the repository will be disabled.
